# Generated by Django 5.1.1 on 2024-09-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeltrainingdata',
            old_name='classes',
            new_name='label',
        ),
    ]
